### ISSUE TITLE
Model in eval forever after the first log on validation

### ISSUE THREAD

**Issue by DavideA** [ermongroup/ncsn#2]
Hi,
and thank you for your work.

I think there may be a bug in the anneal_runner, due to the log of dsm loss on validation. Specifically, the model is put in `eval()` in the following line

https://github.com/ermongroup/ncsn/blob/c4654a258e54a7da0c916132cebdd0818fae8fd2/runners/anneal_runner.py#L158

and it is never put in `train()` again.

Best,
D

**Comment by yang-song** [comment]
Thanks for spotting this! I have just fixed this in the code. Luckily this should not affect the results, since the current model has the same behavior during training and eval.
