### ISSUE TITLE
Custom dataset

### ISSUE THREAD

**Issue by ivder** [ermongroup/ncsn#3]
Hi thanks for the great work. Because I couldn't find any information about custom dataset, I wonder if this repo works for training and generating using custom dataset? If yes, do I have to  convert my images to (for example) Cifar10 format?

**Comment by yang-song** [comment]
This repo is designed for images of 28x28x1 (such as MNIST) and 32x32x3 (such as CIFAR-10). To directly use the repo for generation tasks, you might need to convert your images to one of those formats. That being said, it should be relatively straightforward to modify the architecture for other image resolutions and you are more than welcome to try and tune your own architectures!
