### ISSUE TITLE
Why need adding noise twice

### ISSUE THREAD

**Issue by zhikaili** [ermongroup/ncsn#8]
Hi,

Thank you for the paper and code.

I notice that when training with the annealing strategy, the samples is corrupted twice -- the first one is [here](https://github.com/ermongroup/ncsn/blob/7f27f4a16471d20a0af3be8b8b4c2ec57c8a0bc1/runners/anneal_runner.py#L136), and the second one is [here](https://github.com/ermongroup/ncsn/blob/7f27f4a16471d20a0af3be8b8b4c2ec57c8a0bc1/losses/dsm.py#L31). In my understanding, the second one corresponds to \{ \sigma_1, ... \sigma_L \} described in the paper. May I ask why the first one is needed? 

Thank you and look forward to your reply!

**Comment by yang-song** [comment]
The first one is called dequantization, a common technique used to convert discrete data to continuous distributions. You can find it in flow models as well. It is however optional and can be completely removed in score-based generative models.

**Comment by zhikaili** [comment]
@yang-song Thank you for your prompt reply!
